language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

env:
  - DJANGO=Django==1.6.1
  - DJANGO=https://github.com/django/django/tarball/master

install:
  - pip install $DJANGO
  - pip install pytest==2.5.1 pytest-django==2.5 py==1.4.19
  - pip install coverage==3.7.1 coveralls

script:
  - coverage run -a --rcfile .coveragerc-travis runtests.py transaction_hooks/test --tb short

matrix:
  exclude:
   - python: 2.6
     env: DJANGO=https://github.com/django/django/tarball/master

after_success: coveralls
