language: python

env:
  global:
    - DTC_MYSQL_USERNAME=travis
    - DTC_PG_USERNAME=postgres

install: travis_retry pip install tox coveralls

before_script:
  - mysql -e 'create database dtc;'
  - psql -c 'create database dtc;' -U postgres

script: tox

after_success: coveralls
